# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import internal.protos.review_management.review_management_pb2 as review__management__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in review_management_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReviewManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_review = channel.unary_unary(
            '/ReviewManagement/create_review',
            request_serializer=review__management__pb2.CreateReviewRequest.SerializeToString,
            response_deserializer=review__management__pb2.ReviewOperationResponse.FromString,
            _registered_method=True)
        self.delete_review = channel.unary_unary(
            '/ReviewManagement/delete_review',
            request_serializer=review__management__pb2.DeleteReviewRequest.SerializeToString,
            response_deserializer=review__management__pb2.ReviewOperationResponse.FromString,
            _registered_method=True)


class ReviewManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_review(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_review(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReviewManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'create_review': grpc.unary_unary_rpc_method_handler(
            servicer.create_review,
            request_deserializer=review__management__pb2.CreateReviewRequest.FromString,
            response_serializer=review__management__pb2.ReviewOperationResponse.SerializeToString,
        ),
        'delete_review': grpc.unary_unary_rpc_method_handler(
            servicer.delete_review,
            request_deserializer=review__management__pb2.DeleteReviewRequest.FromString,
            response_serializer=review__management__pb2.ReviewOperationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ReviewManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'ReviewManagement', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.


class ReviewManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_review(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReviewManagement/create_review',
            review__management__pb2.CreateReviewRequest.SerializeToString,
            review__management__pb2.ReviewOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_review(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReviewManagement/delete_review',
            review__management__pb2.DeleteReviewRequest.SerializeToString,
            review__management__pb2.ReviewOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
