# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: review_management.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'review_management.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17review_management.proto\"V\n\x13\x43reateReviewRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\x0c\n\x04rate\x18\x03 \x01(\x02\x12\x0c\n\x04text\x18\x04 \x01(\t\":\n\x13\x44\x65leteReviewRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\".\n\x17ReviewOperationResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x32\x94\x01\n\x10ReviewManagement\x12?\n\rcreate_review\x12\x14.CreateReviewRequest\x1a\x18.ReviewOperationResponse\x12?\n\rdelete_review\x12\x14.DeleteReviewRequest\x1a\x18.ReviewOperationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'review_management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_CREATEREVIEWREQUEST']._serialized_start = 27
    _globals['_CREATEREVIEWREQUEST']._serialized_end = 113
    _globals['_DELETEREVIEWREQUEST']._serialized_start = 115
    _globals['_DELETEREVIEWREQUEST']._serialized_end = 173
    _globals['_REVIEWOPERATIONRESPONSE']._serialized_start = 175
    _globals['_REVIEWOPERATIONRESPONSE']._serialized_end = 221
    _globals['_REVIEWMANAGEMENT']._serialized_start = 224
    _globals['_REVIEWMANAGEMENT']._serialized_end = 372
# @@protoc_insertion_point(module_scope)
