# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_management/order_management.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'order_management/order_management.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'order_management/order_management.proto\"<\n\x15OrderOperationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\"-\n\x16OrderOperationResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x32\x94\x01\n\x0fOrderManagement\x12>\n\x0b\x61\x64\x64_product\x12\x16.OrderOperationRequest\x1a\x17.OrderOperationResponse\x12\x41\n\x0e\x64\x65lete_product\x12\x16.OrderOperationRequest\x1a\x17.OrderOperationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'order_management.order_management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_ORDEROPERATIONREQUEST']._serialized_start = 43
    _globals['_ORDEROPERATIONREQUEST']._serialized_end = 103
    _globals['_ORDEROPERATIONRESPONSE']._serialized_start = 105
    _globals['_ORDEROPERATIONRESPONSE']._serialized_end = 150
    _globals['_ORDERMANAGEMENT']._serialized_start = 153
    _globals['_ORDERMANAGEMENT']._serialized_end = 301
# @@protoc_insertion_point(module_scope)
